import turtle
turtle.shape("turtle")
turtle.speed(1)

size = int(input("введите длину стороны"))
turtle.penup()
turtle.forward(size/2)
turtle.left(90)
turtle.pendown()
turtle.forward(size/2)
turtle.left(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(size/2)